# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-10 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address1', models.TextField()),
                ('Address2', models.TextField()),
                ('City', models.TextField()),
                ('State', models.TextField()),
                ('Zip', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AppStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField()),
                ('updateDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('TaxID', models.TextField()),
                ('Phone', models.TextField()),
                ('NAICS', models.TextField()),
                ('HasBeenProfitable', models.BooleanField()),
                ('HasBankruptedInLast7Years', models.BooleanField()),
                ('InceptionDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CFApplicationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RequestedLoanAmount', models.FloatField()),
                ('StatedCreditHistory', models.TextField()),
                ('LegalEntityType', models.TextField()),
                ('FilterID', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Owners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('FirstName', models.TextField()),
                ('LastName', models.TextField()),
                ('Email', models.EmailField(max_length=254)),
                ('HomeAddress', models.TextField()),
                ('DateOfBirth', models.TextField()),
                ('HomePhone', models.TextField()),
                ('SSN', models.TextField()),
                ('PercentageOfOwnership', models.FloatField()),
                ('Business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Owners', to='webapp.Business')),
            ],
        ),
        migrations.CreateModel(
            name='RequestHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CFRequestId', models.TextField()),
                ('RequestDate', models.DateTimeField()),
                ('CFApiUserId', models.TextField()),
                ('CFApiPassword', models.TextField()),
                ('IsTestLead', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SelfReportedCashFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AnnualRevenue', models.FloatField()),
                ('MonthlyAverageBankBalance', models.FloatField()),
                ('MonthlyAverageCreditCardVolume', models.FloatField()),
                ('Business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SelfReportedCashFlow', to='webapp.Business')),
            ],
        ),
        migrations.AddField(
            model_name='cfapplicationdata',
            name='RequestHeader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CFApplicationData', to='webapp.RequestHeader'),
        ),
        migrations.AddField(
            model_name='business',
            name='RequestHeader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RequestHeader', to='webapp.RequestHeader'),
        ),
        migrations.AddField(
            model_name='appstatus',
            name='RequestHeader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StatusRequestHeader', to='webapp.RequestHeader'),
        ),
        migrations.AddField(
            model_name='address',
            name='Business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Address', to='webapp.Business'),
        ),
        migrations.AddField(
            model_name='address',
            name='Owners',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Address', to='webapp.Owners'),
        ),
    ]
