# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-10 06:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appstatus',
            name='RequestHeader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AppStatus', to='webapp.RequestHeader'),
        ),
    ]
